src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>The description of the project</description>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the project.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <label>Expected Result</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Case__c</fullName>
        <label>Test Case</label>
        <referenceTo>Test_Case__c</referenceTo>
        <relationshipLabel>Steps</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Step</label>
    <nameField>
        <displayFormat>TS-{000000000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>The description of the Test Case</description>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Preconditions__c</fullName>
        <description>The preconditions of the Test Case</description>
        <label>Preconditions</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>The project that the test case is related to.</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Test Cases</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The title of the Test Case</description>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <description>The link to the user story which the test case is related to.</description>
        <label>User Story</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ControllersTest.cls
@isTest
private class ControllersTest {

	@isTest static void testgetStepsTDController() {
		Test_Case__c example = new Test_Case__c();
		example.Id = 'a061I000002O1DHQA0';
		example.Project__c = 'a071I000001JQpHQAW';
		example.User_Story__c = 'http://www.elobservador.com';
		List<Step__c> actual_value = TestDetailsController.getSteps(example);
		List<Step__c> expected_value = [SELECT Name, Description__c, Expected_Result__c, Test_Case__c FROM Step__c WHERE Test_Case__c = :example.Id LIMIT 10000];
		System.assertEquals(expected_value,actual_value);
	}

	@isTest static void testgetProjectsTabController() {
		List<Project__c> expected_value = [SELECT Id, Name, Status__c, OwnerId FROM Project__c ORDER BY Name LIMIT 10000];
		List<Project__c> actual_value = TabsController.getProjects();
		System.assertEquals(expected_value, actual_value);

	}

	@isTest static void testgetOngoingProjectsTabsController(){
		List<Project__c> expected_value = [SELECT Id, Name, Status__c, OwnerId FROM Project__c WHERE Status__c = 'Ongoing' ORDER BY Name LIMIT 10000];
		List<Project__c> actual_value = TabsController.getOngoingProjects();
		System.assertEquals(expected_value, actual_value);
	}

	@isTest static void testgetTestCasesTabsController(){
		List<Test_Case__c> expected_value = [SELECT Id, Title__c, Name, Description__c, Project__c, Preconditions__c, User_Story__c FROM Test_Case__c ORDER BY Name LIMIT 10000];
		List<Test_Case__c> actual_value = TabsController.getTestCases();
		System.assertEquals(expected_value, actual_value);
	}

	@isTest static void testgetRelatedTCTabsController(){
		Project__c example = new Project__c();
		example.Id = 'a071I000001JQpHQAW';
		example.Status__c = 'Ongoing';
		List<Test_Case__c> expected_value = [SELECT Id, Title__c, Name, Description__c, Project__c, Preconditions__c, User_Story__c, LastModifiedDate FROM Test_Case__c  WHERE Project__c = 'a071I000001JQpHQAW' ORDER BY LastModifiedDate DESC LIMIT 10000];
		List<Test_Case__c> actual_value = TabsController.getRelatedTC(example);
		System.assertEquals(expected_value, actual_value);
	}

	@isTest static void testremoveTCandaddTestTabsandTestController(){
		Test_Case__c tc = new Test_Case__c();
		tc.Title__c= 'Test';
		tc.User_Story__c='http://www.google.com.uy';
		tc.Project__c='a071I000001JQpHQAW';
		tc = FTestController.addTestCase(tc);

		List<Test_Case__c> results = [SELECT Id FROM Test_Case__c WHERE Id = :tc.Id];
		Test_Case__c result = results.get(0);

		System.assertEquals(tc.Id, result.Id);

		TabsController.removeTC(tc);
		List<Test_Case__c> empty = new List<Test_Case__c>();

		System.assertEquals(empty, [SELECT Id, Name FROM Test_Case__c WHERE Id = :tc.Id]);
	}

	@isTest static void testupdateTestCaseTabsController(){
		Test_Case__c tc = new Test_Case__c();
		tc.Title__c= 'Test';
		tc.User_Story__c='http://www.google.com.uy';
		tc.Project__c='a071I000001JQpHQAW';
		tc.Preconditions__c = 'Old preconditions';
		tc = FTestController.addTestCase(tc);

		String oldPreconditions = tc.Preconditions__c;
		tc.Preconditions__c = 'New preconditions';

		Test_Case__c returnedValue = TabsController.updateTestCase(tc);
		System.assertEquals(tc.Preconditions__c, returnedValue.Preconditions__c);

		tc.Preconditions__c = oldPreconditions;
		TabsController.updateTestCase(tc);
	}

	@isTest static void testgetProjectsFTestController(){
		List<Project__c> expected_value = [SELECT Id, Name, Status__c, OwnerId FROM Project__c ORDER BY Name LIMIT 10000];
		List<Project__c> actual_value = FTestController.getProjects();
		System.assertEquals(expected_value, actual_value);
	}

	@isTest static void testgetOPProjectsFTestController(){
		List<Project__c> expected_value = [SELECT Id, Name, Status__c, OwnerId FROM Project__c WHERE ((Status__c = 'Ongoing') OR (Status__c = 'Proposed')) ORDER BY Name LIMIT 10000];
		List<Project__c> actual_value = FTestController.getOPProjects();
		System.assertEquals(expected_value, actual_value);
	}

	@isTest static void testinsertTestStep(){
		Step__c example = new Step__c();
		example.Description__c = 'Example Step';
		example.Expected_Result__c = 'Example Step';
		example.Test_Case__c = 'a061I000002O1DHQA0';

		FStepController.insertTestStep(example);

		Step__c insertedValue = [SELECT Id FROM Step__c WHERE Id = : example.Id];

		System.assertEquals(example.Id,insertedValue.Id);
	}

}