src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the project.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <description>The project that the test case is related to.</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Test Cases</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/scheduledEmail.cls
global class scheduledEmail implements Schedulable  {

	global void execute(SchedulableContext SC) {

		 sendmail();

	}
	public void sendmail()
			{
					Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
					List<Project__c> projects = TabsController.getOngoingProjects();
					List<String> owners = new List<String>();
					for(Project__c p : projects){
						owners.add(p.OwnerId);
					}
					List<String> addresses = new List<String>();

					List<User> users = [SELECT Id, Name, SenderEmail FROM User WHERE Id IN : owners];

					for(User u : users){
						addresses.add(u.SenderEmail);
					}

					Integer index = 0;
					String message = '';

					for(String a : addresses){
						String name = users[index].Name;
						String id = users[index].Id;
						List<String> sendTo = new List<String>();
						sendTo.add(a);

						message = 'Hi, ' + name + '\n' + 'This is a list of your ongoing projects' + '\n';
						for(Project__c p : projects){
							if(p.OwnerId == id){
								message = message + 'Name: ' + p.Name + '- Status: ' + p.Status__c + ' ';
								List<AggregateResult> queryResult = [SELECT COUNT_DISTINCT(Id) total FROM Test_Case__c WHERE Project__c = : p.Id];
								Integer countOfTC = (Integer) queryResult[0].get('total');
								message = message + '- Number of associated Test Cases: ' + countOfTC + '\n';
							}
						}
						email.setSubject('List of Ongoing Projects');
						email.setPlainTextBody(message);
						email.setToAddresses(sendTo);
						Messaging.sendEmail(New Messaging.SingleEmailMessage[]{email});
						index++;

					}

			}

}