src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>The description of the project</description>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the project.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>The description of the Test Case</description>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Preconditions__c</fullName>
        <description>The preconditions of the Test Case</description>
        <label>Preconditions</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>The project that the test case is related to.</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Test Cases</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The title of the Test Case</description>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <description>The link to the user story which the test case is related to.</description>
        <label>User Story</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TabsController.cls
public with sharing class TabsController {

    @AuraEnabled
    public static List<Project__c> getProjects(){
        return [SELECT Id, Name, Status__c, OwnerId FROM Project__c ORDER BY Name LIMIT 10000];
    }

		@AuraEnabled
    public static List<Project__c> getOngoingProjects(){
        return [SELECT Id, Name, Status__c, OwnerId FROM Project__c WHERE Status__c = 'Ongoing' ORDER BY Name LIMIT 10000];
    }

    @AuraEnabled
    public static List<Test_Case__c> getTestCases(){
        return [SELECT Id, Title__c, Name, Description__c, Project__c, Preconditions__c, User_Story__c FROM Test_Case__c ORDER BY Name LIMIT 10000];
    }

    @AuraEnabled
    public static List<Test_Case__c> getRelatedTC(Project__c project){
        return [SELECT Id, Title__c, Name, Description__c, Project__c, Preconditions__c, User_Story__c, LastModifiedDate FROM Test_Case__c  WHERE Project__c = : project.Id ORDER BY LastModifiedDate DESC LIMIT 10000];
    }

    @AuraEnabled
    public static void removeTC(Test_Case__c tc) {

      Database.DeleteResult dr = Database.delete(tc);
    }

    @AuraEnabled
    public static Test_Case__c updateTestCase(Test_Case__c selectedTC){

        Database.SaveResult sr = Database.update(selectedTC);
        return selectedTC;
  }
}