src/objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <label>Expected Result</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test_Case__c</fullName>
        <label>Test Case</label>
        <referenceTo>Test_Case__c</referenceTo>
        <relationshipLabel>Steps</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Step</label>
    <nameField>
        <displayFormat>TS-{000000000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>The description of the Test Case</description>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDetailsController.cls
public with sharing class TestDetailsController {

	@AuraEnabled
	public static List<Step__c> getSteps(Test_Case__c tc){
		return [SELECT Id, Name, Description__c, Expected_Result__c, Test_Case__c, Order__c FROM Step__c WHERE Test_Case__c = :tc.Id ORDER BY Order__c ASC LIMIT 10000];

	}

	@AuraEnabled
	public static List<Step__c> updateSteps(List<Step__c> steps, String tcId){
		Database.SaveResult[] srList = Database.update(steps);

		for(Database.SaveResult sr : srList){
			if(sr.isSuccess()){
				System.debug('Update was ok' + sr);
			}
			else{
				for(Database.Error err : sr.getErrors()) {
            System.debug('The following error has occurred.');
            System.debug(err.getStatusCode() + ': ' + err.getMessage());
            System.debug('Contact fields that affected this error: ' + err.getFields());	 }
			}
		}

		return [SELECT Id, Name, Description__c, Expected_Result__c, Test_Case__c, Order__c FROM Step__c WHERE Test_Case__c = :tcId ORDER BY Order__c ASC LIMIT 10000];
		
	}
}