src/objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test_Case__c</fullName>
        <label>Test Case</label>
        <referenceTo>Test_Case__c</referenceTo>
        <relationshipLabel>Steps</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Step</label>
    <nameField>
        <displayFormat>TS-{000000000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Test_Case__c.object
<CustomObject>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FStepController.cls
public with sharing class FStepController {

	@AuraEnabled
	public static void insertTestStep(Step__c step){


		List<Step__c> query  = [SELECT Order__c FROM Step__c WHERE Test_Case__c = : step.Test_Case__c ORDER BY Order__c DESC];
		if (!query.isEmpty()){
			Step__c lastStep = query.get(0);
			step.Order__c = lastStep.Order__c + 1;
			Database.SaveResult sr = Database.insert(step);

				if(sr.isSuccess()){
					System.debug('Insert was ok' + sr);
				}
				else{
					for(Database.Error err : sr.getErrors()) {
	            System.debug('The following error has occurred.');
	            System.debug(err.getStatusCode() + ': ' + err.getMessage());
	            System.debug('Contact fields that affected this error: ' + err.getFields());
						 }
				}

		}
		else{
			step.Order__c = 0;
			Database.SaveResult sr = Database.insert(step);

				if(sr.isSuccess()){
					System.debug('Insert was ok' + sr);
				}
				else{
					for(Database.Error err : sr.getErrors()) {
	            System.debug('The following error has occurred.');
	            System.debug(err.getStatusCode() + ': ' + err.getMessage());
	            System.debug('Contact fields that affected this error: ' + err.getFields());
						 }
				}
		}
	}

}